# Конфигурация для Render.com
services:
  # Backend
  - type: web
    name: dashboard-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_HOST
        value: pg4.sweb.ru
      - key: DB_PORT
        value: 5433
      - key: DB_USER
        value: headcorne_test
      - key: DB_PASSWORD
        value: Ss8SRGP5TH3W6J@L
      - key: DB_NAME
        value: headcorne_test
      - key: PLANFIX_API_URL
        value: https://megamindru.planfix.ru/rest/
      - key: PLANFIX_API_TOKEN
        value: 3325457cab2f1a9b69b3c9191eeadc82
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: APP_NAME
        value: Dashboard Service
      - key: DEBUG
        value: False
      - key: CORS_ORIGINS
        sync: false

  # Frontend
  - type: web
    name: dashboard-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html




